<?php
/**
 * @file
 * Code for the ABC Base feature.
 */

include_once 'abc_base.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function abc_base_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['wide_header'] = array(
    'label' => t('Wide Header'),
    'pane category' => t('ABC - General'),
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/wide_header',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

  $entity_info['fieldable_panels_pane']['bundles']['wide_image_rotator'] = array(
    'label' => t('Wide Image Rotator'),
    'pane category' => t('ABC - General'),
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/wide_image_rotator',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_panels_pane().
 */
function abc_base_preprocess_panels_pane(&$vars) {
  if ($vars['content']['#bundle'] == 'wide_header') {
    $color_field = field_get_items(
      'fieldable_panels_pane',
      $vars['content']['#fieldable_panels_pane'],
      'field_color'
    );
    if ($color_field) {
      $vars['classes_array'][] = 'has-color';
      $vars['classes_array'][] = 'color-' . $color_field[0]['value'];
    }
  }

  if ($vars['content']['#bundle'] == 'wide_image_rotator') {
    drupal_add_js(drupal_get_path('module', 'abc_base') . '/js/wide_image_rotator.js');
  }
}

